apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: ladeit
    name: ladeit
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: ladeit
    template:
      metadata:
        labels:
          app: ladeit
      spec:
        containers:
        - image: ladeit/ladeit:latest
          imagePullPolicy: Always
          name: ladeit
          ports:
          - containerPort: 8000
            protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8000
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8000
              scheme: HTTP
            periodSeconds: 60
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 1500m
              memory: 3Gi
            requests:
              cpu: 500m
              memory: 1Gi
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ladeit
    name: ladeit
  spec:
    ports:
    - name: ladeit
      port: 8000
      protocol: TCP
      targetPort: 8000
    selector:
      app: ladeit
    type: ClusterIP